#!/usr/bin/env zsh

[[ -f ~/.dj ]] && . ~/.dj

album=$1
first_disc=${2:-1}

src=$DJ_SCRATCH
dest=$DJ_MUSIC/$album

if [[ -z $2 && -d $dest ]]; then
    echo "Already exists: $dest" > /dev/stderr
    exit 1
fi

mkdir -p $dest

num_discs=$((`grep ^~~~$ $album | wc -l` + 1))

for disc in {01..$num_discs}; do
    [[ $disc -lt $first_disc ]] && continue

    echo "--- Insert disc $(($disc)) of $num_discs ---"
    while cdrecord -toc 2>&1 | grep -q 'Cannot load media'; do sleep 1; done
    echo "Ripping via external ripper..."
    $DJ_EXTERNAL_RIPPER
    cdrecord -eject > /dev/null 2>&1

    tracknum=0
    for track in $src/*.flac; do
        destfile="$dest/disc${disc}track`basename $track`"

        echo "Archiving track $((tracknum+=1))..."
        cp -i $track $destfile

        echo "Verifying track $tracknum..."
        diff -q $track $destfile || exit 2

        rm $track
    done

    echo
done
